variables:
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: laravel
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: laravel
  DB_HOST: mysql

cache:
  paths:
    - backend/vendor/

stages:
  - test

.config:
  image: php:8.2-fpm
  services:
    - mysql:latest
  before_script:
    - cd ./backend
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    - apt-get update && apt-get install -y libzip-dev zip libpng-dev libfreetype6-dev libjpeg62-turbo-dev
    - docker-php-ext-configure pcntl --enable-pcntl
    - docker-php-ext-install pcntl zip
    - docker-php-ext-install pdo_mysql
    - docker-php-ext-configure gd --with-freetype --with-jpeg
    - docker-php-ext-install gd
    - pecl install redis
    - docker-php-ext-enable redis
    - chmod -R 755 .
    - cp .env.example .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - mkdir -p storage/framework/{sessions,views,cache}
    - php artisan storage:link
    - php artisan optimize:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan event:cache
    - php artisan migrate --force
    - php artisan key:generate
    - php artisan key:generate --env=testing

check:
  stage: test
  extends:
    - .config
  script:
    - php vendor/bin/phpunit --no-coverage --colors=never
