variables:
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: laravel
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: laravel
  DB_HOST: mysql

cache:
  paths:
    - backend/vendor/

stages:
  - test

.config:
  image: php:8.2-fpm
  services:
    - name: mysql:latest
    - name: redis:latest
  before_script:
    - cd ./backend
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    - apt-get update && apt-get install -y libzip-dev zip libpng-dev libfreetype6-dev libjpeg62-turbo-dev
    - docker-php-ext-configure pcntl --enable-pcntl
    - docker-php-ext-install pcntl zip
    - docker-php-ext-install pdo_mysql
    - docker-php-ext-configure gd --with-freetype --with-jpeg
    - docker-php-ext-install gd
    - cp .env.testing .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - php artisan key:generate
    - mkdir -p storage/framework/{sessions,views,cache}
    - php artisan config:clear
    - php artisan config:clear --env=testing
    - php artisan cache:clear
    - php artisan cache:clear --env=testing
    - php artisan storage:link
    - php artisan optimize:clear
    - php artisan optimize:clear --env=testing
    - php artisan config:cache
    - php artisan config:cache --env=testing
    - php artisan route:cache
    - php artisan view:cache
    - php artisan event:cache
    - chmod -R 755 .
    - php artisan migrate:fresh

check:
  stage: test
  extends:
    - .config
  script:
    - php -m
    - php artisan test --parallel --no-coverage --colors=never
